### ISSUE TITLE
Non serializable with new AminoAcid object method?

### ISSUE THREAD

**Issue by KyleStiers** [lafita/mmtf-fragment-search#3]
I pulled down the new version with AminoAcid implementation for grabbing phi/psi's but now I'm getting errors (builds successfully) at runtime about serialization. Any idea how to fix it? It seems the issue-causing line is: 

`.mapToPair(new SimilarityScorer(query))`

which comes from:
`private AminoAcidImpl[] query;` 

Is this the same serialization issue we had with 'Group[]'? Does yours run successfully?

**Comment by lafita** [comment]
Sorry, I had forgotten to update to the current BioJava development branch. The latest commit I submitted sets the development branch of BioJava as the latest. If you pull the master you should get the changes.

Let me know if it works for you (works for me now).

**Comment by KyleStiers** [comment]
I pulled the master and see the changes you've made, however am still getting the same runtime error of: `at edu.sdsc.main.FragmentSearch.main(FragmentSearch.java:70)
Caused by: java.io.NotSerializableException: org.biojava.nbio.structure.Model` 

(line 70 is `.mapToPair(new SimilarityScorer(query))`). Can't figure out why. Maybe I should try starting completely fresh.

**Comment by lafita** [comment]
Ok, I think you need to clone the biojava source code and import it to eclipse to get the latest development build. Try following these steps and let me know if it works:

1. `git clone git@github.com:biojava/biojava.git`
2. In eclipse: File > Import > Existing Maven projects > (select the path where you cloned biojava)
3. Run As > Maven install on the biojava folder
4. Maven > Update Project... > (select all)

Sorry for the complicated setup, but the good thing is that you will be using the most up to date code of the library. You can also explore the packages and source code.

**Comment by lafita** [comment]
Now it should be working even without cloning locally biojava (because there was a new alpha release with the serialization fixes)

**Comment by KyleStiers** [comment]
Thanks! I may have accidentally issued a pull request, sorry about that. Trying out a new git GUI called GitKraken for windows as MobaXTerm hasn't been playing nicely with git. Anywho, I've been entirely unable to get things to build successfully on windows, so I'll try this when I'm home with my laptop.

I think in the future, we should maybe have a 'stable' branch that maybe stays with full releases of BioJava and dependencies, and a dev version which incorporates all the newest features. If we get users they'll most likely just want a stable version.

**Comment by lafita** [comment]
I think for now the whole project is a development stage, if we believe the code is ready for other people to use it we should invest some time in documentation and project management, as you suggest. Maybe we can create a separate issue to discuss that!
